# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a8d24d4f8c58018c2c5f83220ee8226d7599a59969227b00497e6c1a02e45ed3450f68339cc231b84d8c6570ad9c2fe2c83c57c58dd108c325479bede75867bb

test:
  secret_key_base: 34d476532055df0f71ed123b960b6db6c941e12c8b7bdf169bb733a7b7125da0e53a755196a6c30f8fa18ed2ebb70a1d6e4b18d5f5eda34346fb6ca698a24475

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
